root_dir: "d:/王驰中的经历/研究生/研一下课程/自然语言处理/secondKarlMarx"

models:
  default_chat_model:
    model: "gpt-3.5-turbo"
    type: "openai_chat"
    auth_type: "api_key"
    api_key: "sk-ZhF2CPvVSjuqOZOk5n2fbancon1CTyxWzS1TtQx84JB5GQOY"
    api_base: "https://www.dmxapi.cn/v1"
  
  default_embedding_model:
    model: "text-embedding-ada-002"
    type: "openai_embedding"
    auth_type: "api_key"
    api_key: "sk-ZhF2CPvVSjuqOZOk5n2fbancon1CTyxWzS1TtQx84JB5GQOY"
    api_base: "https://www.dmxapi.cn/v1"

input:
  type: "file"
  file_type: "json"
  base_dir: "d:/王驰中的经历/研究生/研一下课程/自然语言处理/secondKarlMarx/test_chunks"
  # Avoid using glob patterns completely
  file_pattern: ""
  encoding: "utf-8"
  text_column: "raw_text"
  metadata:
    - "metadata"

chunks:
  strategy: "tokens"
  size: 10000
  overlap: 0
  encoding_model: "cl100k_base"

vector_store:
  default_vector_store:
    type: "lancedb"
    db_uri: "d:/王驰中的经历/研究生/研一下课程/自然语言处理/secondKarlMarx/lancedb"
    overwrite: true

output:
  type: "file"
  base_dir: "d:/王驰中的经历/研究生/研一下课程/自然语言处理/secondKarlMarx/graphrag_output"

cache:
  type: "memory"

embed_text:
  model_id: "default_embedding_model"
  vector_store_id: "default_vector_store"
  batch_size: 16
  batch_max_tokens: 8191
