model_name_or_path: Qwen/Qwen2.5-7B-Instruct

stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,k_proj,v_proj,o_proj
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.1

dataset: ChizhongWang/secondKarlMarx-sft
dataset_format: alpaca
dataset_columns:
  prompt: prompt
  response: content
template: qwen
cutoff_len: 8192
max_samples: 2  # 只使用前两个样本进行测试
preprocessing_num_workers: 4

output_dir: ./outputs_llama_factory_test
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 2.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true

deepspeed: configs/ds_config_zero2.json
