# 马克思恩格斯知识图谱GraphRAG配置文件

# 模型配置
models:
  # 聊天模型配置
  default_chat_model:
    type: openai
    model: gpt-3.5-turbo
    encoding_model: cl100k_base
    api_key: ${DMX_API_KEY}
    api_base: https://www.dmxapi.cn/v1
    temperature: 0
    max_tokens: 2048
  
  # 嵌入模型配置
  default_embedding_model:
    type: openai
    model: text-embedding-ada-002
    encoding_model: cl100k_base
    api_key: ${DMX_API_KEY}
    api_base: https://www.dmxapi.cn/v1

# 输入配置
input:
  type: file
  file_type: text
  base_dir: "../data/processed"  # 相对于配置文件的路径
  encoding: "utf-8"

# 输出配置
output:
  type: file
  base_dir: "../kg/output"  # 相对于配置文件的路径

# 缓存配置
cache:
  type: file
  base_dir: "../models/cache"

# 文本分块配置
chunks:
  size: 1000  # 每个文本块的大小（以token为单位）
  overlap: 100  # 文本块之间的重叠（以token为单位）
  strategy: tokens

# 图提取配置
extract_graph:
  entity_types:
    - PERSON
    - ORGANIZATION
    - LOCATION
    - DATE
    - EVENT
    - WORK_OF_ART
    - CONCEPT
  strategy:
    prompt_template_path: /home/featurize/secondKarlMarx/graphrag/graphrag/index/operations/extract_graph/prompts/extract_graph.prompt
    examples_path: /home/featurize/secondKarlMarx/graphrag/graphrag/index/operations/extract_graph/prompts/extract_graph_examples.json
    entity_name_column: title
    entity_type_column: type
    entity_description_column: description
    source_entity_column: source
    target_entity_column: target
    relationship_description_column: description
    relationship_strength_column: strength
  max_gleanings: 5  # 每个文本块提取的最大实体数量

# 文本嵌入配置
embed_text:
  model: "text-embedding-3-small"
  batch_size: 16
  target: all

# 向量存储配置
vector_store:
  default_vector_store:
    type: lancedb
    db_uri: "../models/vector_store"
    container_name: "marx_engels"
    overwrite: true

# 查询配置
local_search:
  text_unit_prop: 0.6  # 文本相关性权重
  community_prop: 0.4  # 社区相关性权重
  top_k_entities: 15   # 返回的最大实体数量
  top_k_relationships: 10  # 返回的最大关系数量

# 路径配置
paths:
  data:
    input: /home/featurize/secondKarlMarx/marx_kg/data/processed/marx_engels_documents.json
    output: /home/featurize/secondKarlMarx/marx_kg/data/kg
  cache:
    root: /home/featurize/secondKarlMarx/marx_kg/data/cache

# 日志配置
logging:
  level: INFO
